import { count } from 'console'
import type { NextPage, NextPageContext } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRecoilState } from 'recoil'
import styles from '../styles/Home.module.css'
import { countAtom, countSelector } from './model/countState'

const Top: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Counter />
      </body>
    </div>
  )
}

export default function Counter() {
  const [countValue, countSet] = useRecoilState(countAtom)
  return (
    <>
      <div>{countValue}</div>
      <button onClick={() => countSet(countValue + 1)}>aaa</button>
    </>
  )
}
